import { describe, it } from 'node:test'
import assert from 'node:assert'
import { typeGenerator } from './typeGenerator.js'

void describe('typeGenerator', () => {
	void it(`should return the type tree definition given the id of a LwM2M object defined in a XML format`, () => {
		const result = typeGenerator('14201')
		const expected = [
			{
				pos: -1,
				end: -1,
				flags: 16,
				modifierFlagsCache: 0,
				transformFlags: 1,
				parent: undefined,
				kind: 265,
				symbol: undefined,
				localSymbol: undefined,
				modifiers: [
					{
						pos: -1,
						end: -1,
						flags: 16,
						modifierFlagsCache: 0,
						transformFlags: 0,
						parent: undefined,
						kind: 95,
					},
				],
				name: {
					pos: -1,
					end: -1,
					flags: 16,
					modifierFlagsCache: 0,
					transformFlags: 0,
					parent: undefined,
					kind: 80,
					escapedText: 'Geolocation_14201',
					jsDoc: undefined,
					flowNode: undefined,
					symbol: undefined,
				},
				typeParameters: undefined,
				type: {
					pos: -1,
					end: -1,
					flags: 16,
					modifierFlagsCache: 0,
					transformFlags: 1,
					parent: undefined,
					kind: 183,
					typeName: {
						pos: -1,
						end: -1,
						flags: 16,
						modifierFlagsCache: 0,
						transformFlags: 0,
						parent: undefined,
						kind: 80,
						escapedText: 'Readonly',
						jsDoc: undefined,
						flowNode: undefined,
						symbol: undefined,
					},
					typeArguments: [],
				},
				jsDoc: undefined,
				locals: undefined,
				nextContainer: undefined,
				emitNode: { leadingComments: [[Object]] },
			},
			{
				pos: -1,
				end: -1,
				flags: 16,
				modifierFlagsCache: 0,
				transformFlags: 1,
				parent: undefined,
				kind: 265,
				symbol: undefined,
				localSymbol: undefined,
				modifiers: undefined,
				name: {
					pos: -1,
					end: -1,
					flags: 16,
					modifierFlagsCache: 0,
					transformFlags: 0,
					parent: undefined,
					kind: 80,
					escapedText: 'Latitude_0',
					jsDoc: undefined,
					flowNode: undefined,
					symbol: undefined,
				},
				typeParameters: undefined,
				type: {
					pos: -1,
					end: -1,
					flags: 16,
					modifierFlagsCache: 0,
					transformFlags: 1,
					parent: undefined,
					kind: 183,
					typeName: {
						pos: -1,
						end: -1,
						flags: 16,
						modifierFlagsCache: 0,
						transformFlags: 0,
						parent: undefined,
						kind: 80,
						escapedText: 'number',
						jsDoc: undefined,
						flowNode: undefined,
						symbol: undefined,
					},
					typeArguments: undefined,
				},
				jsDoc: undefined,
				locals: undefined,
				nextContainer: undefined,
				emitNode: { leadingComments: [[Object]] },
			},
			{
				pos: -1,
				end: -1,
				flags: 16,
				modifierFlagsCache: 0,
				transformFlags: 1,
				parent: undefined,
				kind: 265,
				symbol: undefined,
				localSymbol: undefined,
				modifiers: undefined,
				name: {
					pos: -1,
					end: -1,
					flags: 16,
					modifierFlagsCache: 0,
					transformFlags: 0,
					parent: undefined,
					kind: 80,
					escapedText: 'Longitude_1',
					jsDoc: undefined,
					flowNode: undefined,
					symbol: undefined,
				},
				typeParameters: undefined,
				type: {
					pos: -1,
					end: -1,
					flags: 16,
					modifierFlagsCache: 0,
					transformFlags: 1,
					parent: undefined,
					kind: 183,
					typeName: {
						pos: -1,
						end: -1,
						flags: 16,
						modifierFlagsCache: 0,
						transformFlags: 0,
						parent: undefined,
						kind: 80,
						escapedText: 'number',
						jsDoc: undefined,
						flowNode: undefined,
						symbol: undefined,
					},
					typeArguments: undefined,
				},
				jsDoc: undefined,
				locals: undefined,
				nextContainer: undefined,
				emitNode: { leadingComments: [[Object]] },
			},
			{
				pos: -1,
				end: -1,
				flags: 16,
				modifierFlagsCache: 0,
				transformFlags: 1,
				parent: undefined,
				kind: 265,
				symbol: undefined,
				localSymbol: undefined,
				modifiers: undefined,
				name: {
					pos: -1,
					end: -1,
					flags: 16,
					modifierFlagsCache: 0,
					transformFlags: 0,
					parent: undefined,
					kind: 80,
					escapedText: 'Timestamp_9',
					jsDoc: undefined,
					flowNode: undefined,
					symbol: undefined,
				},
				typeParameters: undefined,
				type: {
					pos: -1,
					end: -1,
					flags: 16,
					modifierFlagsCache: 0,
					transformFlags: 1,
					parent: undefined,
					kind: 183,
					typeName: {
						pos: -1,
						end: -1,
						flags: 16,
						modifierFlagsCache: 0,
						transformFlags: 0,
						parent: undefined,
						kind: 80,
						escapedText: 'number',
						jsDoc: undefined,
						flowNode: undefined,
						symbol: undefined,
					},
					typeArguments: undefined,
				},
				jsDoc: undefined,
				locals: undefined,
				nextContainer: undefined,
				emitNode: { leadingComments: [[Object]] },
			},
			{
				pos: -1,
				end: -1,
				flags: 16,
				modifierFlagsCache: 0,
				transformFlags: 1,
				parent: undefined,
				kind: 265,
				symbol: undefined,
				localSymbol: undefined,
				modifiers: undefined,
				name: {
					pos: -1,
					end: -1,
					flags: 16,
					modifierFlagsCache: 0,
					transformFlags: 0,
					parent: undefined,
					kind: 80,
					escapedText: 'Altitude_2',
					jsDoc: undefined,
					flowNode: undefined,
					symbol: undefined,
				},
				typeParameters: undefined,
				type: {
					pos: -1,
					end: -1,
					flags: 16,
					modifierFlagsCache: 0,
					transformFlags: 1,
					parent: undefined,
					kind: 183,
					typeName: {
						pos: -1,
						end: -1,
						flags: 16,
						modifierFlagsCache: 0,
						transformFlags: 0,
						parent: undefined,
						kind: 80,
						escapedText: 'number',
						jsDoc: undefined,
						flowNode: undefined,
						symbol: undefined,
					},
					typeArguments: undefined,
				},
				jsDoc: undefined,
				locals: undefined,
				nextContainer: undefined,
				emitNode: { leadingComments: [[Object]] },
			},
			{
				pos: -1,
				end: -1,
				flags: 16,
				modifierFlagsCache: 0,
				transformFlags: 1,
				parent: undefined,
				kind: 265,
				symbol: undefined,
				localSymbol: undefined,
				modifiers: undefined,
				name: {
					pos: -1,
					end: -1,
					flags: 16,
					modifierFlagsCache: 0,
					transformFlags: 0,
					parent: undefined,
					kind: 80,
					escapedText: 'Radius_3',
					jsDoc: undefined,
					flowNode: undefined,
					symbol: undefined,
				},
				typeParameters: undefined,
				type: {
					pos: -1,
					end: -1,
					flags: 16,
					modifierFlagsCache: 0,
					transformFlags: 1,
					parent: undefined,
					kind: 183,
					typeName: {
						pos: -1,
						end: -1,
						flags: 16,
						modifierFlagsCache: 0,
						transformFlags: 0,
						parent: undefined,
						kind: 80,
						escapedText: 'number',
						jsDoc: undefined,
						flowNode: undefined,
						symbol: undefined,
					},
					typeArguments: undefined,
				},
				jsDoc: undefined,
				locals: undefined,
				nextContainer: undefined,
				emitNode: { leadingComments: [[Object]] },
			},
			{
				pos: -1,
				end: -1,
				flags: 16,
				modifierFlagsCache: 0,
				transformFlags: 1,
				parent: undefined,
				kind: 265,
				symbol: undefined,
				localSymbol: undefined,
				modifiers: undefined,
				name: {
					pos: -1,
					end: -1,
					flags: 16,
					modifierFlagsCache: 0,
					transformFlags: 0,
					parent: undefined,
					kind: 80,
					escapedText: 'Speed_4',
					jsDoc: undefined,
					flowNode: undefined,
					symbol: undefined,
				},
				typeParameters: undefined,
				type: {
					pos: -1,
					end: -1,
					flags: 16,
					modifierFlagsCache: 0,
					transformFlags: 1,
					parent: undefined,
					kind: 183,
					typeName: {
						pos: -1,
						end: -1,
						flags: 16,
						modifierFlagsCache: 0,
						transformFlags: 0,
						parent: undefined,
						kind: 80,
						escapedText: 'number',
						jsDoc: undefined,
						flowNode: undefined,
						symbol: undefined,
					},
					typeArguments: undefined,
				},
				jsDoc: undefined,
				locals: undefined,
				nextContainer: undefined,
				emitNode: { leadingComments: [[Object]] },
			},
			{
				pos: -1,
				end: -1,
				flags: 16,
				modifierFlagsCache: 0,
				transformFlags: 1,
				parent: undefined,
				kind: 265,
				symbol: undefined,
				localSymbol: undefined,
				modifiers: undefined,
				name: {
					pos: -1,
					end: -1,
					flags: 16,
					modifierFlagsCache: 0,
					transformFlags: 0,
					parent: undefined,
					kind: 80,
					escapedText: 'Heading_5',
					jsDoc: undefined,
					flowNode: undefined,
					symbol: undefined,
				},
				typeParameters: undefined,
				type: {
					pos: -1,
					end: -1,
					flags: 16,
					modifierFlagsCache: 0,
					transformFlags: 1,
					parent: undefined,
					kind: 183,
					typeName: {
						pos: -1,
						end: -1,
						flags: 16,
						modifierFlagsCache: 0,
						transformFlags: 0,
						parent: undefined,
						kind: 80,
						escapedText: 'number',
						jsDoc: undefined,
						flowNode: undefined,
						symbol: undefined,
					},
					typeArguments: undefined,
				},
				jsDoc: undefined,
				locals: undefined,
				nextContainer: undefined,
				emitNode: { leadingComments: [[Object]] },
			},
		]

		assert.deepEqual(result, expected)
	})
})